branches:
  only:
    - master

os:
  - linux
  - osx

language: ruby

cache:
  directories:
    - $HOME/.rvm
    - $HOME/.cargo
    - $HOME/.rustup

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_VERSION=stable
  matrix:
    - RUBY_TARGET=2.4
    - RUBY_TARGET=2.5
    - RUBY_TARGET=2.6
    - RUBY_TARGET=ruby-head

before_install:
  # Install Rubies
  - rvm reload && rvm get stable
  - rvm install 2.4
  - rvm install 2.5
  - rvm install 2.6
  - rvm install ruby-head
  - for ruby_host in $RUBY_HOSTS; do rvm install $ruby_host; done
  # Install Rust
  - if [ ! -e "$HOME/.cargo/bin" ]; then curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y; fi
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup default $RUST_VERSION
  - rustup update

install:
  - rvm 2.4 do bundle install --jobs=3 --retry=3
  - rvm 2.5 do bundle install --jobs=3 --retry=3
  - rvm 2.6 do bundle install --jobs=3 --retry=3
  - rvm ruby-head do bundle install --jobs=3 --retry=3
  - rvm $RUBY_TARGET do bundle exec rake build:tests

script:
  - rvm use 2.4
  - rm -rf tmp
  - bundle exec rake build:extension
  - bundle exec rake test:run
  - rvm use 2.5
  - rm -rf tmp
  - bundle exec rake build:extension
  - bundle exec rake test:run
  - rvm use 2.6
  - rm -rf tmp
  - bundle exec rake build:extension
  - bundle exec rake test:run
  - rvm use ruby-head
  - rm -rf tmp
  - bundle exec rake build:extension
  - bundle exec rake test:run
