branches:
  only:
    - master

stages:
  - test # default
  - docs

jobs:
  include:
    - stage: docs
      script: IN_PLACE=true rake doc
      rvm: false
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: target/doc

os:
  - linux
  - osx

language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

cache:
  directories:
    - $HOME/.rvm
    - $HOME/.cargo
    - $HOME/.rustup

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_VERSION=stable

before_install:
  # Install Rust
  - if [ ! -e "$HOME/.cargo/bin" ]; then curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y; fi
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup default $RUST_VERSION
  - rustup update
